### ISSUE TITLE
Create a test suite for OSM Stats

### ISSUE THREAD

**Issue by robsavoye** [hotosm/osm-stats-api#11]
The OSM Stats API needs a test suite so it can be validated via a CI system. This will primarily be unit level tests. Each class in the API module should have a test case that imports, and tests all the class methods. This should include using some bad data to test stability of the error handling.

This task will also require a small dedicated test database that can be created from within the test execution. Part of this task is deciding on the best Python testing framework. I use DejaGnu for other Python projects as it's very mature and maintained, but am open to other solutions.

As creating a test suite is a long-term project that never really ends, this task will be complete when there are tests for the currently existing functionality as of Oct, 2021, which at this stage is still relatively small.

**Comment by itskshitiz321** [comment]
Related to #7
