### ISSUE TITLE
[BUG] Fix issues in Tasking Manager Stats related endpoints

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/osm-stats-api#271]
@raytoun has noticed the following issues with Tasking Manager stats related endpoints:
* Team Statistics: this endpoint should include only active team members. At present it includes inactive team members too
* Project stats on validated tasks returning incorrect numbers - number of tasks validated is more than the available tasks
* Project endpoint should include all projects including those which does not have any activity 
* Project endpoint should lt filtering by project status.

cc @kshitijrajsharma

**Comment by kshitijrajsharma** [comment]
Team Statistics : Only include active team Members 
> This /tasking-manager/teams should only return active team members , currently it is returning inactive members too

**Comment by kshitijrajsharma** [comment]
Feature : Add status filter on tasking manager validation stats 
Project endpoint should be filtering by project status.

**Comment by kshitijrajsharma** [comment]
Feature : Filter TM validation stats by organisation id 
Validation endpoint should be able to filter output by respective organization id
