### ISSUE TITLE
Issues when installing

### ISSUE THREAD

**Issue by NicolasGrosjean** [hotosm/osm-stats-api#304]
Hello,

I wonder if I can help on this project like I have good knowledge on Python programming.

Like I have no ideas how to start, I tried to install locally the API.

Following the Readme, I succeed to display the page of the endpoints but no one works because of a lake of config.

I have only "understand" 2 sections:

- RAW_DATA is the configuration of the Postgis database. I used the service Postgis from the underpass [docker-compose](https://github.com/hotosm/underpass/blob/master/docker/docker-compose.yml) to setup this.
- SENTRY can removed to work otherwise I get the error `sentry_sdk.utils.BadDsn: Missing public key` maybe because the default config values are not enough

Where can I have documentation on other config sections ?

I also did some suggestions on the install with the pull request found below.
Do not hesitate to close that pull request and/or this issue if it isn't efficient for you and let me know how I can better contribute to this project.

**Comment by kshitijrajsharma** [comment]
Hi @NicolasGrosjean Thank you for looking at the repo , And I am very excited to hear that ! Definitely we are working on the documentation , I will raise a PR with config block documentation with further guide to set it up !
