### ISSUE TITLE
Add Development setup guide for developers 

### ISSUE THREAD

**Issue by kshitijrajsharma** [hotosm/osm-stats-api#307]
Hi @NicolasGrosjean Thank you for looking at the repo , And I am very excited to hear that ! Definitely we are working on the documentation , I will raise a PR with config block documentation with further guide to set it up !

_Originally posted by @kshitijrajsharma in https://github.com/hotosm/galaxy-api/issues/304#issuecomment-1214640738_

**Comment by kshitijrajsharma** [comment]
cc: @petya-kangalova @ramyaragupathy

**Comment by petya-kangalova** [comment]
@NicolasGrosjean thank you so much for contributing to the Galaxy API repository!! As @kshitijrajsharma  said that is very exciting! I work for HOT as open tech collective facilitator and really interested in hearing from contributors and seeing how we can better support the contributor community. Will be very happy to have a chat if you are interested !

**Comment by NicolasGrosjean** [comment]
Thank you for welcoming.
@petya-kangalova I am also interested to have a chat. I sent you an email about it.
