### ISSUE TITLE
< ANNOUNCEMENT > : RAW DATA EXTRACTION IS BEING MIGRATED 

### ISSUE THREAD

**Issue by kshitijrajsharma** [hotosm/osm-stats-api#348]
Raw data extraction feature of Galaxy API is being migrated to export-tool-api which will take galaxy api as base and all development related to extraction of geometry will be done in https://github.com/hotosm/export-tool-api 
This will affect /rawdata api and further more will not be available under galaxy API !

**Comment by jeafreezy** [comment]
This is a great move. Separation of concern!
